config/routes.rb
Rails.application.routes.draw do
  get 'user/new'
  get 'user/create'
  get 'user/show'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "home#index"
  resources :home
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
    has_many :user_events, foreign_key: :attended_event_id
    has_many :event_attenders, through: :user_events, source: :event_attender
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'creator_id'
  has_many :user_events, foreign_key: 'event_attender_id'
  has_many :attended_events, through: :user_events
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :event_attender, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!
def index 
 @events = Event.all.order('created_at Desc')
end
  def attend
    @event = Event.find(params[:id])
    current_user.events << @event
    redirect_to @event, notice: 'You have promised to attend this event.'
  end

def show
@event = Event.find(params[:id])
	end

def new
@event = Event.new
end

def create
@event = current_user.events.build(event_params)
 respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
end

def update

	end

def destroy
@event = Event.find(params[:id])
@event.destroy
redirect_to root_path
end

private

def event_params
params.require(:event).permit(:start_time, :end_time, :title, :description)
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def show
  	@events = current_user.events.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_events_cta.html.erb
<div class="container my-4">
<%= image_tag 's.svg' %>
<h1>It looks like you havn't scheduled a session yet</h1>
</div>

<%= link_to 'Schedule New Session', new_event_path, class:'btn btn-success' %>

app/views/events/_events_landing.html.erb
<div class="container">
	<h1>
		Welcome <%= current_user.name %>, this is your list of events 
	</h1>

	<h3>Upcoming Events:</h3>
	<% if @upcoming_events %>
<%=  @upcoming_events.each do |event| %>
<%= link_to event.title, event %>
	<% end %>
	<% else %>
	<h3>There is No Upcoming Events</h3>
	<% end %>
	<h3>Past Events:</h3>
	<% if @past_events%>
		<% @past_events.each do |event| %>
		<%= link_to event.title, event %><br>
		<% end %>
	<% end %>
	<%= link_to 'Schedule New Session', new_event_path, class:'btn btn-success' %>
	<%= link_to 'Back To Dashboard', home_index_path, class:'btn btn-secondary' %>
</div>

app/views/events/index.html.erb
<div class="container">
	<!-- if user has any meetings to show -->
	<% unless current_user.events.any? %>
<%= render 'events_cta' %>
	<% else %>
	<!-- here i am passing variable from index method from the controller  -->
<%= render 'events_landing', events: @events %>
	<% end %>
</div>

app/views/events/new.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.button :submit %>
<% end %>

app/views/events/show.html.erb
<div class="position-relative">
 <div class="card" style="width: 22rem; margin:5% auto;">
  <div class="card-body">
    <h5 class="card-title"><%= @event.title %></h5>
    <p class="card-text"><%= @event.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Start Time:
		<%= @event.start_time %></li>
    <li class="list-group-item">End Time:
		<%= @event.end_time %></li>
     <li class="list-group-item">
      <p>Event created by: <%= @event.creator.name %></p>
     </li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link"><%= link_to "Back", events_path, class:'btn btn-secondary' %></a>
    <a href="#" class="card-link"><%= link_to 'Edit', edit_event_path, class:'btn btn-secondary' %></a>
    <a href="#" class="card-link"><%= link_to 'Delete', event_path(@event), method: :delete, class:'btn btn-secondary' %></a>

  </div>
  <%= link_to 'Attend', new_user_event_path %>
</div>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Private Events</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to 'Dashboard', events_path, class:'btn btn-success' %>
        </li>
      </ul>
    
    </div>
      <div class="d-flex float-end">
        <% if user_signed_in? %>
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, data: { confirm: 'Are You Sure?' }, class:'btn pink' %>
        <%= link_to current_user.name, user_show_path, class:'btn pink' %>
        <% else %>
        <%= link_to 'Log In', new_user_session_path, class:'btn pink mx-3' %>
        <%= link_to 'Sign In', new_user_registration_path, class:'btn pink' %>
        <% end %>
      </div>
  </div>
</nav>

<div class="position-relative">
  <div class="position-absolute top-50 start-50 translate-middle">
  <h3>Welcome to the Private Events Application <br>
  This is part of Microverse Project <br>
  Hope You Will Like It</h3>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assocations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
	<h1>
		Welcome <%= current_user.name %>, this is your list of events 
	</h1>
	<% @events.each do |e| %>
	<%= link_to e.title, e %><br>
	<% end %>

	<%= link_to 'Back To Dashboard', home_index_path, class:'btn btn-success' %>